/** Country options for onboarding — curated global list. */
export const COUNTRIES: string[] = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Spain",
  "Brazil",
  "Mexico",
  "Nigeria",
  "India",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Thailand",
  "Malaysia",
  "Singapore",
  "Japan",
  "South Korea",
  "Taiwan",
  "Hong Kong",
  "Bangladesh",
  "Pakistan",
  "Other",
];
