/** Country options for onboarding — Asia-first (Kreav's focus), then global. */
export const COUNTRIES: string[] = [
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Thailand",
  "Malaysia",
  "Singapore",
  "India",
  "Japan",
  "South Korea",
  "Taiwan",
  "Hong Kong",
  "Bangladesh",
  "Pakistan",
  "United States",
  "United Kingdom",
  "Australia",
  "Canada",
  "Germany",
  "Other",
];
